from __future__ import annotations
import uuid
from datetime import datetime
from sqlalchemy import JSON, DateTime, ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
class Base(DeclarativeBase): pass
class Repository(Base):
    __tablename__="repositories"; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); display_name:Mapped[str]=mapped_column(String(200)); canonical_path:Mapped[str]=mapped_column(Text,unique=True); default_branch:Mapped[str]=mapped_column(String(200)); ingestion_status:Mapped[str]=mapped_column(String(30),default="registered")
class Commit(Base):
    __tablename__="commits"; __table_args__=(UniqueConstraint("repository_id","sha"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); sha:Mapped[str]=mapped_column(String(64)); parent_shas:Mapped[list]=mapped_column(JSON); message:Mapped[str]=mapped_column(Text); author_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); committer_time:Mapped[datetime]=mapped_column(DateTime(timezone=True))
class SourceSnapshot(Base):
    __tablename__="source_snapshots"; __table_args__=(UniqueConstraint("repository_id","source_identity","content_hash"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); source_identity:Mapped[str]=mapped_column(Text); source_type:Mapped[str]=mapped_column(String(30)); source_version:Mapped[str]=mapped_column(String(100)); content_hash:Mapped[str]=mapped_column(String(64)); text:Mapped[str]=mapped_column(Text); locator:Mapped[dict]=mapped_column(JSON); available_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); ingested_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); provenance_quality:Mapped[str]=mapped_column(String(30))
class Record(Base):
    __tablename__="domain_records"; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("repositories.id"),index=True); kind:Mapped[str]=mapped_column(String(40),index=True); stable_key:Mapped[str]=mapped_column(Text); version:Mapped[int]=mapped_column(default=1); payload:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); __table_args__=(UniqueConstraint("kind","stable_key","version"),)

class EvidenceSpan(Base):
    __tablename__="evidence_spans"; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); snapshot_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("source_snapshots.id"),index=True); exact_quote:Mapped[str]=mapped_column(Text); start_line:Mapped[int]; end_line:Mapped[int]; start_offset:Mapped[int]; end_offset:Mapped[int]; validation_result:Mapped[str]=mapped_column(String(30))
class DecisionVersion(Base):
    __tablename__="decision_versions"; __table_args__=(UniqueConstraint("repository_id","decision_key","version"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); decision_key:Mapped[str]=mapped_column(String(200)); version:Mapped[int]; statement:Mapped[str]=mapped_column(Text); rationale:Mapped[str]=mapped_column(Text); scope:Mapped[list]=mapped_column(JSON); exceptions:Mapped[list]=mapped_column(JSON); proposal_evidence_ids:Mapped[list]=mapped_column(JSON); acceptance_evidence_ids:Mapped[list]=mapped_column(JSON); effective_anchor:Mapped[str|None]=mapped_column(String(40)); lifecycle_status:Mapped[str]=mapped_column(String(30),index=True)
class DecisionRelation(Base):
    __tablename__="decision_relations"; __table_args__=(UniqueConstraint("source_version_id","target_version_id","kind","anchor"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); source_version_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("decision_versions.id")); target_version_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("decision_versions.id")); kind:Mapped[str]=mapped_column(String(30)); scope:Mapped[list]=mapped_column(JSON); anchor:Mapped[str|None]=mapped_column(String(40)); evidence_ids:Mapped[list]=mapped_column(JSON); status:Mapped[str]=mapped_column(String(30))
class SymbolSnapshot(Base):
    __tablename__="symbol_snapshots"; __table_args__=(UniqueConstraint("repository_id","revision","path","qualified_name","signature_hash"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); revision:Mapped[str]=mapped_column(String(40),index=True); path:Mapped[str]=mapped_column(Text); qualified_name:Mapped[str]=mapped_column(Text); kind:Mapped[str]=mapped_column(String(30)); signature_hash:Mapped[str]=mapped_column(String(64)); span:Mapped[dict]=mapped_column(JSON)
class ImportEdge(Base):
    __tablename__="import_edges"; __table_args__=(UniqueConstraint("repository_id","revision","source_path","raw_specifier","edge_kind","line"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); revision:Mapped[str]=mapped_column(String(40),index=True); source_path:Mapped[str]=mapped_column(Text); source_symbol:Mapped[str|None]=mapped_column(Text); raw_specifier:Mapped[str]=mapped_column(Text); resolved_target:Mapped[str|None]=mapped_column(Text); edge_kind:Mapped[str]=mapped_column(String(30)); resolution_status:Mapped[str]=mapped_column(String(30)); type_only:Mapped[bool]; line:Mapped[int]
class RuleVersion(Base):
    __tablename__="rule_versions"; __table_args__=(UniqueConstraint("decision_version_id","version"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); decision_version_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("decision_versions.id")); version:Mapped[int]; family:Mapped[str]=mapped_column(String(40)); schema_version:Mapped[int]; parameters:Mapped[dict]=mapped_column(JSON); content_hash:Mapped[str]=mapped_column(String(64)); approval_state:Mapped[str]=mapped_column(String(30)); activation_scope:Mapped[list]=mapped_column(JSON)
class ReviewEvent(Base):
    __tablename__="review_events"; __table_args__=(UniqueConstraint("idempotency_key"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); target_id:Mapped[uuid.UUID]=mapped_column(index=True); target_version:Mapped[int]; content_hash:Mapped[str]=mapped_column(String(64)); action:Mapped[str]=mapped_column(String(30)); reviewer:Mapped[str]=mapped_column(String(200)); rationale:Mapped[str]=mapped_column(Text); idempotency_key:Mapped[str]=mapped_column(String(200)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class AnalysisRun(Base):
    __tablename__="analysis_runs"; __table_args__=(UniqueConstraint("repository_id","idempotency_key"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); base_sha:Mapped[str]=mapped_column(String(40)); head_sha:Mapped[str]=mapped_column(String(40)); evidence_cutoff:Mapped[datetime]=mapped_column(DateTime(timezone=True)); policy_snapshot:Mapped[dict]=mapped_column(JSON); provider_config:Mapped[dict]=mapped_column(JSON); checker_version:Mapped[str]=mapped_column(String(50)); mode:Mapped[str]=mapped_column(String(30)); status:Mapped[str]=mapped_column(String(30),index=True); outputs:Mapped[dict]=mapped_column(JSON); idempotency_key:Mapped[str]=mapped_column(String(200))
class Finding(Base):
    __tablename__="findings"; __table_args__=(UniqueConstraint("analysis_id","rule_version_id","fingerprint","disposition"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); analysis_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("analysis_runs.id"),index=True); rule_version_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("rule_versions.id")); path:Mapped[str]=mapped_column(Text); span:Mapped[dict]=mapped_column(JSON); evidence_ids:Mapped[list]=mapped_column(JSON); disposition:Mapped[str]=mapped_column(String(30)); severity:Mapped[str]=mapped_column(String(20)); support_status:Mapped[str]=mapped_column(String(30)); fingerprint:Mapped[str]=mapped_column(String(64))
class Job(Base):
    __tablename__="jobs"; __table_args__=(UniqueConstraint("idempotency_key"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("repositories.id"),index=True); type:Mapped[str]=mapped_column(String(40)); payload:Mapped[dict]=mapped_column(JSON); status:Mapped[str]=mapped_column(String(30),index=True); idempotency_key:Mapped[str]=mapped_column(String(200)); attempts:Mapped[int]; max_attempts:Mapped[int]; worker_id:Mapped[str|None]=mapped_column(String(100)); lease_expiry:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); heartbeat:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); progress:Mapped[dict]=mapped_column(JSON); error:Mapped[dict|None]=mapped_column(JSON)
class EvaluationCase(Base):
    __tablename__="evaluation_cases"; __table_args__=(UniqueConstraint("repository_id","case_key"),); id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); repository_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("repositories.id"),index=True); case_key:Mapped[str]=mapped_column(String(200)); split:Mapped[str]=mapped_column(String(30)); group_name:Mapped[str]=mapped_column(String(100)); inputs:Mapped[dict]=mapped_column(JSON); expected:Mapped[dict]=mapped_column(JSON)
