import json,os,subprocess
from intentledger.checker import compare,scan

def commit(repo,message):
 env={**os.environ,"GIT_AUTHOR_NAME":"test","GIT_AUTHOR_EMAIL":"test@example.invalid","GIT_COMMITTER_NAME":"test","GIT_COMMITTER_EMAIL":"test@example.invalid"};subprocess.run(["git","-C",repo,"add","."],check=True,env=env);subprocess.run(["git","-C",repo,"commit","-m",message],check=True,env=env,capture_output=True);return subprocess.check_output(["git","-C",repo,"rev-parse","HEAD"],text=True).strip()
def test_alias_barrel_transitive(tmp_path):
 repo=tmp_path/"repo";repo.mkdir();subprocess.run(["git","-C",repo,"init","-b","main"],check=True,capture_output=True);(repo/"src/services").mkdir(parents=True);(repo/"src/infra").mkdir();(repo/"tsconfig.json").write_text(json.dumps({"compilerOptions":{"baseUrl":".","paths":{"@app/*":["src/*"]}}}));(repo/"src/infra/sdk.ts").write_text("import sdk from 'payment-sdk'; export default sdk;\n");(repo/"src/infra/index.ts").write_text("export {default as sdk} from './sdk';\n");(repo/"src/services/a.ts").write_text("export const ok=1;\n");base=commit(repo,"base");(repo/"src/services/a.ts").write_text("import {sdk} from '@app/infra'; export const bad=sdk;\n");head=commit(repo,"head");rule={"kind":"adapter_boundary","scope":["src/services/**"],"protected_packages":["payment-sdk"],"allowed_adapter_paths":[],"mode":"transitive","include_type_only":False};result=compare(str(repo),base,head,rule);assert result["execution"]=="fail";assert result["findings"][0]["disposition"]=="introduced";assert result["findings"][0]["path"][-1]=="payment-sdk"
def test_nonliteral_is_unsupported(tmp_path):
 repo=tmp_path/"repo";repo.mkdir();subprocess.run(["git","-C",repo,"init","-b","main"],check=True,capture_output=True);(repo/"a.ts").write_text("const name='x'; import(name);\n");rev=commit(repo,"dynamic");_,_,limits=scan(str(repo),rev,{"kind":"forbidden_import","scope":["**"],"forbidden_targets":["x"]});assert "non-literal dynamic loading" in limits[0]
