import ts from "typescript";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
type Edge={source:string;specifier:string;target?:string;kind:string;typeOnly:boolean;status:string};
const fail=(error:string)=>({contract_version:1,status:"error",error,limitations:[]});
function filesAt(repo:string,rev:string):string[]{return execFileSync("git",["-C",repo,"ls-tree","-r","--name-only",rev],{encoding:"utf8"}).split("\n").filter(x=>/\.(ts|tsx)$/.test(x));}
function analyze(repo:string,rev:string){const edges:Edge[]=[];const limitations:string[]=[];for(const file of filesAt(repo,rev)){const text=execFileSync("git",["-C",repo,"show",`${rev}:${file}`],{encoding:"utf8",maxBuffer:2e6});const sf=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true);sf.forEachChild(function walk(n){if(ts.isImportDeclaration(n)||ts.isExportDeclaration(n)){const m=n.moduleSpecifier;if(m&&ts.isStringLiteral(m))edges.push({source:file,specifier:m.text,kind:ts.isExportDeclaration(n)?"export":"import",typeOnly:!!n.importClause?.isTypeOnly,status:"observed"});}else if(ts.isCallExpression(n)){const name=n.expression.getText(sf);if(name==="require"||n.expression.kind===ts.SyntaxKind.ImportKeyword){if(n.arguments.length&&ts.isStringLiteral(n.arguments[0]))edges.push({source:file,specifier:n.arguments[0].text,kind:name==="require"?"require":"dynamic_import",typeOnly:false,status:"observed"});else limitations.push(`${file}:${sf.getLineAndCharacterOfPosition(n.pos).line+1}: non-literal dynamic loading`);}}ts.forEachChild(n,walk)});}return {contract_version:1,status:limitations.length?"unsupported":"ok",edges,symbols:[],limitations};}
let input="";process.stdin.setEncoding("utf8");process.stdin.on("data",c=>input+=c);process.stdin.on("end",()=>{try{const q=JSON.parse(input);if(q.contract_version!==1||!/^[0-9a-f]{40}$/.test(q.revision))throw Error("invalid v1 request");process.stdout.write(JSON.stringify(analyze(path.resolve(q.repository),q.revision)));}catch(e){process.stdout.write(JSON.stringify(fail(String(e))))}});
